// Code generated by Slice Machine. DO NOT EDIT.

import BigText from './BigText';
import ContactForm from './ContactForm';
import Image from './Image';
import Projects from './Projects';
import Quote from './Quote';
import SmallText from './SmallText';
import Text from './Text';

export {
	BigText,
	ContactForm,
	Image,
	Projects,
	Quote,
	SmallText,
	Text,
};

export const components = {
	big_text: BigText,
	contact_form: ContactForm,
	image: Image,
	projects: Projects,
	quote: Quote,
	small_text: SmallText,
	text: Text,
};
